#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 5010

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["WebApiApplicationServiceV2.csproj", ""]
RUN dotnet restore "WebApiApplicationServiceV2.csproj"
COPY . .
RUN dotnet build "WebApiApplicationServiceV2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebApiApplicationServiceV2.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApiApplicationServiceV2.dll"]